/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface FileManagerInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "FileCreated" | "FileDeleted" | "FilesImported"
  ): EventFragment;
}

export namespace FileCreatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDeletedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FilesImportedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FileManager extends BaseContract {
  connect(runner?: ContractRunner | null): FileManager;
  waitForDeployment(): Promise<this>;

  interface: FileManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "FileCreated"
  ): TypedContractEvent<
    FileCreatedEvent.InputTuple,
    FileCreatedEvent.OutputTuple,
    FileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FileDeleted"
  ): TypedContractEvent<
    FileDeletedEvent.InputTuple,
    FileDeletedEvent.OutputTuple,
    FileDeletedEvent.OutputObject
  >;
  getEvent(
    key: "FilesImported"
  ): TypedContractEvent<
    FilesImportedEvent.InputTuple,
    FilesImportedEvent.OutputTuple,
    FilesImportedEvent.OutputObject
  >;

  filters: {
    "FileCreated()": TypedContractEvent<
      FileCreatedEvent.InputTuple,
      FileCreatedEvent.OutputTuple,
      FileCreatedEvent.OutputObject
    >;
    FileCreated: TypedContractEvent<
      FileCreatedEvent.InputTuple,
      FileCreatedEvent.OutputTuple,
      FileCreatedEvent.OutputObject
    >;

    "FileDeleted()": TypedContractEvent<
      FileDeletedEvent.InputTuple,
      FileDeletedEvent.OutputTuple,
      FileDeletedEvent.OutputObject
    >;
    FileDeleted: TypedContractEvent<
      FileDeletedEvent.InputTuple,
      FileDeletedEvent.OutputTuple,
      FileDeletedEvent.OutputObject
    >;

    "FilesImported()": TypedContractEvent<
      FilesImportedEvent.InputTuple,
      FilesImportedEvent.OutputTuple,
      FilesImportedEvent.OutputObject
    >;
    FilesImported: TypedContractEvent<
      FilesImportedEvent.InputTuple,
      FilesImportedEvent.OutputTuple,
      FilesImportedEvent.OutputObject
    >;
  };
}
