/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type FileStruct = {
  _name: string;
  _fileType: string;
  _ipfsHash: string;
  _key: string;
  _sharedBy: AddressLike;
};

export type FileStructOutput = [
  _name: string,
  _fileType: string,
  _ipfsHash: string,
  _key: string,
  _sharedBy: string
] & {
  _name: string;
  _fileType: string;
  _ipfsHash: string;
  _key: string;
  _sharedBy: string;
};

export interface VaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSharedFile"
      | "createFile"
      | "deleteFile"
      | "getAllFiles"
      | "getCreator"
      | "getOwner"
      | "getUser"
      | "migrateFiles"
      | "user"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FileCreated"
      | "FileDeleted()"
      | "FileDeleted()"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSharedFile",
    values: [string, string, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createFile",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "deleteFile", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAllFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "getUser", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "migrateFiles",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike, FileStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "user", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addSharedFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createFile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deleteFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCreator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrateFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;
}

export namespace FileCreatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDeleted__Event {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDeleted__Event {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Vault extends BaseContract {
  connect(runner?: ContractRunner | null): Vault;
  waitForDeployment(): Promise<this>;

  interface: VaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSharedFile: TypedContractMethod<
    [
      name: string,
      fileType: string,
      ipfsHash: string,
      key: string,
      sharedBy: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  createFile: TypedContractMethod<
    [name: string, fileType: string, ipfsHash: string, key: string],
    [void],
    "nonpayable"
  >;

  deleteFile: TypedContractMethod<[ipfsHash: string], [void], "nonpayable">;

  getAllFiles: TypedContractMethod<[], [FileStructOutput[]], "view">;

  getCreator: TypedContractMethod<[], [string], "view">;

  getOwner: TypedContractMethod<[], [string], "view">;

  getUser: TypedContractMethod<[], [string], "view">;

  migrateFiles: TypedContractMethod<
    [
      _hashedMessage: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _files: FileStruct[]
    ],
    [void],
    "nonpayable"
  >;

  user: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSharedFile"
  ): TypedContractMethod<
    [
      name: string,
      fileType: string,
      ipfsHash: string,
      key: string,
      sharedBy: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createFile"
  ): TypedContractMethod<
    [name: string, fileType: string, ipfsHash: string, key: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteFile"
  ): TypedContractMethod<[ipfsHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllFiles"
  ): TypedContractMethod<[], [FileStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getCreator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "migrateFiles"
  ): TypedContractMethod<
    [
      _hashedMessage: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _files: FileStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "user"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FileCreated"
  ): TypedContractEvent<
    FileCreatedEvent.InputTuple,
    FileCreatedEvent.OutputTuple,
    FileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FileDeleted()"
  ): TypedContractEvent<
    FileDeleted__Event.InputTuple,
    FileDeleted__Event.OutputTuple,
    FileDeleted__Event.OutputObject
  >;
  getEvent(
    key: "FileDeleted()"
  ): TypedContractEvent<
    FileDeleted__Event.InputTuple,
    FileDeleted__Event.OutputTuple,
    FileDeleted__Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FileCreated()": TypedContractEvent<
      FileCreatedEvent.InputTuple,
      FileCreatedEvent.OutputTuple,
      FileCreatedEvent.OutputObject
    >;
    FileCreated: TypedContractEvent<
      FileCreatedEvent.InputTuple,
      FileCreatedEvent.OutputTuple,
      FileCreatedEvent.OutputObject
    >;

    "FileDeleted()": TypedContractEvent<
      FileDeleted__Event.InputTuple,
      FileDeleted__Event.OutputTuple,
      FileDeleted__Event.OutputObject
    >;
    "FileDeleted()": TypedContractEvent<
      FileDeleted__Event.InputTuple,
      FileDeleted__Event.OutputTuple,
      FileDeleted__Event.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
